apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-label
  template:
    metadata:
      labels:
        app: server-label
    spec:
      containers:
      - name: server-api
        image: f2499r/node-app:latest
        ports:
        - containerPort: 8080

